[colors.primary]
background = "0x000000"

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 9

[scrolling]
history = 10000
multiplier = 1

[shell]
args = ["-c", "nix develop path:./Config-Files/shell/nix --quiet"]
program = "bash"

[window]
dynamic_title = true
opacity = 0.7
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 8
y = 8

[window.position]
x = 100
y = 100
