[pyprland]
plugins = [ "scratchpads", "wallpapers" ]

[scratchpads.term]
animation = "fromTop"
command = "ghostty --class=com.mitchellh.ghostty.scratchpad"
class = "com.mitchellh.ghostty.scratchpad"
size = "70% 60%"
position = "15% 20%"

[scratchpads.pomodoro]
animation = "fromTop"
command = "pomodoro"
class = "io.gitlab.idevecore.Pomodoro"
size = "20% 20%"
position = "40% 40%"

[scratchpads.keepassxc]
animation = "fromTop"
command = "keepassxc"
class = "org.keepassxc.KeePassXC"
size = "80% 70%"
position = "10% 15%"

[scratchpads.mullvad-vpn]
animation = "fromTop"
command = "mullvad-vpn"
class = "Mullvad VPN"

[wallpapers]
unique = true # unique for each monitor
path = "~/Pictures/Wallpapers/Favorite"
interval = 30 # minutes
extensions = ["jpg", "jpeg", "png"]
command = 'swww img --transition-type grow "[file]"'
clear_command = "swww clear"
